In [8]:
import random
import time
import numpy as np 
a = []
for i in range(1000000):
    a.append(random.random())
t1 = time.time()
sum1 = sum(a)
t2 = time.time()
b = np.array(a)
t4 = time.time()
sum3 = np.sum(b)
t5 = time.time()
print(t2-t1,t5-t4)

0.00399017333984375 0.0021224021911621094


In [13]:
a= np.array([[1,2,3],[4,5,6]])
b = np.array([1,2,3,4])
c = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(a.shape)
print(b.shape)
print(c.shape)

(2, 3)
(4,)
(2, 2, 3)


In [14]:
import numpy as np
score = np.array([[80, 89, 86, 67, 79],
[78, 97, 89, 67, 81],
[90, 94, 78, 67, 74],
[91, 91, 90, 67, 69],
[76, 87, 75, 67, 86],
[70, 79, 84, 67, 84],
[94, 92, 93, 67, 64],
[86, 85, 83, 67, 80]])
print(type(score.dtype))

<class 'numpy.dtype'>


In [15]:
a = np.array([[1,2,3],[4,5,6]],dtype = np.float32)
a.dtype

dtype('float32')

In [16]:
arr = np.array(['pyhton','tensorflow','scikit-learn','numpy'],dtype= np.string_)
arr

array([b'pyhton', b'tensorflow', b'scikit-learn', b'numpy'], dtype='|S12')

In [17]:
zero = np.zeros([3,4])
zero

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
a = np.array([[1,2,3],[4,5,6]])
a1 = np.array(a)
a2 = np.asarray(a)
print(a1)
print(a2)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]


In [20]:
data = np.ones([3,4])
data

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [21]:
data1 = np.array(data)

In [22]:
data2 = np.asarray(data)

In [23]:
data1,data2

(array([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]),
 array([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]))

In [24]:
data[1] = 2

In [25]:
data2

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [1., 1., 1., 1.]])

In [26]:
data1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [28]:
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [29]:
np.arange(10,50,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [2]:
import numpy as np 
a = np.array([1,2,3,4,5],ndmin = 1)
print(a)

[1 2 3 4 5]


In [10]:
import numpy as np
a = np.array([1,2,3],dtype=complex)
print(a)

[1.+0.j 2.+0.j 3.+0.j]


In [11]:
import numpy as np
dt = np.dtype('i4')
print(dt)

int32


In [13]:
dt = np.dtype(np.int32)
print(dt)

int32


In [14]:
dt = np.dtype("<i4")
print(dt)

int32


In [17]:
dt = np.dtype([('age',np.int8)])
print(dt)

[('age', 'i1')]


In [19]:
import numpy as np 
dt = np.dtype([('age',np.int8)])
a= np.array([(10,),(20,),(30,)],dtype = dt)
print(a['age'])

[10 20 30]


In [28]:
import numpy as np
student = np.dtype([('name','S20'), ('age', 'i1'), ('marks', 'f4')]) 
a = np.array([('abc', 21, 50),('xyz', 18, 75)], dtype = student) 
print(a['name'])

[b'abc' b'xyz']


In [36]:
import numpy as np
a = np.arange(24)
print(a.ndim)
b = a.reshape(2,4,3)
print(b.ndim)

1
3


In [37]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
print(a.shape)

(2, 3)


In [42]:
import numpy as np 
a = np.array([[1,2,3],[4,5,6]])
a.shape = (3,2)
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [44]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]]) 
b = a.reshape(3,2)  
print (b)

[[1 2]
 [3 4]
 [5 6]]


In [47]:
import numpy as np 
# 数组dtype 为int8 (一个字节)
x = np.array([1,2,3,4,5],dtype = np.int8)
print(x.itemsize)
# 数组的dtype 为float64 (8个字节)
b = np.array([1,2,3,4,5],dtype = np.float64)
print(b.itemsize)

1
8


In [48]:
import numpy as np
x = np.array([1,2,3,4,5])
print(x.flags)

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False



In [53]:
import numpy as np 
x = np.empty([3,2], dtype = int,order = 'C') 
print (x)

[[900   0]
 [900   0]
 [  1 105]]
